@NLADotNetInternshipTraining.HospitalSystemAppointment_HostAddress = http://localhost:5075

GET {{NLADotNetInternshipTraining.HospitalSystemAppointment_HostAddress}}/weatherforecast/
Accept: application/json

###
